---
- name: Configure static IP addresses on target hosts
  hosts:
    - titan1
    - titan2
    - titan3
    - titan4
  remote_user: root
  become: yes
  vars:
    network_interface: "eno1"
    static_ips:
      titan1: "192.168.3.51"
      titan2: "192.168.3.52"
      titan3: "192.168.3.53"
      titan4: "192.168.3.54"
    netmask: "255.255.255.0"
    broadcast: "192.168.3.255"
    gateway: "192.168.3.1"
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"

  tasks:
    - name: Configure static IP address
      template:
        src: static_ip.j2
        dest: /etc/network/interfaces.d/{{ network_interface }}.cfg

    - name: Disable connman service
      ansible.builtin.systemd:
        name: connman
        state: stopped
        enabled: no

    - name: Restart networking
      ansible.builtin.systemd:
        name: networking
        state: restarted
        enabled: yes
