---
- name: Update /etc/hosts with all titan hosts
  remote_user: root
  hosts:
    - titan1
    - titan2
    - titan3
    - titan4

  vars:
    hosts_entries:
      titan1: "192.168.3.51"
      titan2: "192.168.3.52"
      titan3: "192.168.3.53"
      titan4: "192.168.3.54"

  tasks:
    - name: Add hosts to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ hosts_entries[item.key] }} {{ item.key }}"
        regexp: "^{{ hosts_entries[item.key] }}\\s+{{ item.key }}"
        state: present
      loop: "{{ hosts_entries | dict2items }}"
      when: inventory_hostname != item.key  # Prevent adding the host's own IP with its name

